### ISSUE TITLE
`rosa version` command fails in the openshift CI

### ISSUE THREAD

**Issue by vishnuchalla** [openshift/rosa#1955]
`rosa version` command fails in the openshift CI with below reason.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x19 pc=0x259f7e0]

goroutine 1 [running]:
github.com/openshift/rosa/cmd/version.(*RosaVersionOptions).BindAndValidate(0xc000bbfbb8?, {0x8c?, 0x7a?})
	/go/src/github.com/openshift/rosa/cmd/version/options.go:58
github.com/openshift/rosa/cmd/version.NewRosaVersionCommand.RosaVersionRunner.func2({0x0?, 0x0?}, 0x0?, 0x0?, {0x0?, 0x0?, 0x0?})
	/go/src/github.com/openshift/rosa/cmd/version/cmd.go:64 +0x45
github.com/openshift/rosa/cmd/version.NewRosaVersionCommand.DefaultRunner.func3(0xc000ef2900?, {0x4326fe0, 0x0, 0x0})
	/go/src/github.com/openshift/rosa/pkg/rosa/runner.go:29 +0x10f
github.com/spf13/cobra.(*Command).execute(0xc00024c600, {0x4326fe0, 0x0, 0x0})
	/go/src/github.com/openshift/rosa/vendor/github.com/spf13/cobra/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x4288980)
	/go/src/github.com/openshift/rosa/vendor/github.com/spf13/cobra/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/openshift/rosa/vendor/github.com/spf13/cobra/command.go:1039
main.main()
	/go/src/github.com/openshift/rosa/cmd/rosa/main.go:109 +0x93
```
Looks like something to do with the latest changes that went into `version subcommand`: https://github.com/openshift/rosa/pull/1953
Here is the step that we are using in openshift CI: https://steps.ci.openshift.org/reference/openshift-qe-rosa-loaded-upgrade
And we use latest image tag to fetch rosa cli in our CI config
```
  rosa-aws-cli:
    name: rosa-aws-cli
    namespace: ci
    tag: latest
```

**Comment by jfchevrette** [comment]
Seeing the same runtime error in https://github.com/NixOS/nixpkgs/pull/317409
