### ISSUE TITLE
rosa cli - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by thimslugga** [openshift/rosa#672]
Attempting to login using the latest rosa cli results in errors after input of the offline token and login.

```
$ rosa login
To login to your Red Hat account, get an offline access token at https://console.redhat.com/openshift/token/rosa
? Copy the token and paste it here: ***

I: Logged in as 'my-redhat-username' on 'https://api.openshift.com'
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10faa6e]

goroutine 1 [running]:
github.com/openshift/rosa/pkg/ocm.(*Client).Close(...)
	/home/pvasanth/go/src/gitlab.cee.redhat.com/service/rosa/pkg/ocm/client.go:151
github.com/openshift/rosa/cmd/login.run.func1()
	/home/pvasanth/go/src/gitlab.cee.redhat.com/service/rosa/cmd/login/cmd.go:255 +0x2e
panic({0x1411c20, 0x25465e0})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/openshift/rosa/pkg/ocm.(*Client).GetConnectionTokens(...)
	/home/pvasanth/go/src/gitlab.cee.redhat.com/service/rosa/pkg/ocm/client.go:159
github.com/openshift/rosa/cmd/login.run(0x255d1a0, {0x259c540, 0x0, 0x0})
	/home/pvasanth/go/src/gitlab.cee.redhat.com/service/rosa/cmd/login/cmd.go:260 +0xb76
github.com/spf13/cobra.(*Command).execute(0x255d1a0, {0x259c540, 0x0, 0x0})
	/home/pvasanth/go/src/gitlab.cee.redhat.com/service/rosa/vendor/github.com/spf13/cobra/command.go:856 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x2560da0)
	/home/pvasanth/go/src/gitlab.cee.redhat.com/service/rosa/vendor/github.com/spf13/cobra/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/home/pvasanth/go/src/gitlab.cee.redhat.com/service/rosa/vendor/github.com/spf13/cobra/command.go:897
main.main()
	/home/pvasanth/go/src/gitlab.cee.redhat.com/service/rosa/cmd/rosa/main.go:95 +0x8b
```
It does appear that login was successful despite the errors that were returned.
```
$ rosa whoami
AWS Account ID:               <my-aws-account-id>
AWS Default Region:           us-east-1
AWS ARN:                      arn:aws:iam::<aws-account-id>:role/Admin
OCM API:                      https://api.openshift.com
OCM Account ID:               <ocm-account-id>
OCM Account Name:             <First Last>
OCM Account Username:         <my-redhat-username>
OCM Account Email:            <my-email>
OCM Organization ID:          <my-org-id>
OCM Organization Name:        <my-org-name>
OCM Organization External ID: <org-external-id>
```
```
$ rosa version
1.1.12

$ grep PRETTY /etc/os-release
PRETTY_NAME="Amazon Linux 2"

$ file -s /usr/local/bin/rosa
/usr/local/bin/rosa: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

**Comment by shibumi** [comment]
I am pretty sure the reason for this issue lies here:

https://github.com/openshift/rosa/blob/346dc5eeeaa87384e4ac4bf572baaf30feeba673/cmd/login/cmd.go#L241L259


The returned ocm client seems to be empty. This happens when the configuration file does not exist: https://github.com/openshift/rosa/blob/346dc5eeeaa87384e4ac4bf572baaf30feeba673/pkg/ocm/config.go#L73L83

**Comment by pvasant** [comment]
This has been addressed. Hence closing
